name: outing
description: A Flutter clone of the OutingApp.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.10+1 
  geolocator: ^12.0.0 
  url_launcher: ^6.3.0
  intl: ^0.19.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

# Add this entire section
  lib: any

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/